-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public."Todo"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone DEFAULT now(),
    title text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    CONSTRAINT "Todo_pkey" PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Todo"
    OWNER to postgres;

GRANT ALL ON TABLE public."Todo" TO anon;

GRANT ALL ON TABLE public."Todo" TO authenticated;

GRANT ALL ON TABLE public."Todo" TO postgres;

GRANT ALL ON TABLE public."Todo" TO service_role;

CREATE POLICY "Enable access to all users"
    ON public."Todo"
    AS PERMISSIVE
    FOR SELECT
    TO public
    USING (true);

CREATE POLICY "Enable INSERT for authenticated users only"
    ON public."Todo"
    AS PERMISSIVE
    FOR INSERT
    TO public
    WITH CHECK ((auth.role() = 'authenticated'::text));

CREATE POLICY "Enable DELETE/UPDATE for authenticated users only"
    ON public."Todo"
    AS PERMISSIVE
    FOR ALL
    TO public
    USING ((auth.role() = 'authenticated'::text));

ALTER TABLE IF EXISTS public."Todo"
    ENABLE ROW LEVEL SECURITY;
